id: I7F2F924B
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-18T20:13:26.854500'
last_modified: '2022-06-18T20:13:26.854518'
parser: null
source_metadata:
  title: Prajñāpāramitāsūtra in eight thousand lines (Old Gongkar block print), colophon
    excerpt from Golden manuscript, unrevised
  author: མི་གསལ།
  description: 'Digital version 1.0 {Tibetan}, diplomatic edition of witness A; master
    xml (completed: 2020-05-29); revised, thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Excerpt/Colophon'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:Mathias Fermer (mf)
  - Editorial process:-
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:Mathias Fermer (mf)
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/4861
  bases:
    4d40:
      title: Prajñāpāramitāsūtra in eight thousand lines (Old Gongkar block print),
        colophon excerpt from Golden manuscript, unrevised
      order: 1
      base_file: 4d40.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
